//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServisDevam.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tweet", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Tweet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Twit {
            get {
                return this.TwitField;
            }
            set {
                if ((object.ReferenceEquals(this.TwitField, value) != true)) {
                    this.TwitField = value;
                    this.RaisePropertyChanged("Twit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MyServiceSoap")]
    public interface MyServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServisDevam.ServiceReference1.HelloWorldResponse HelloWorld(WebServisDevam.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebServisDevam.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pisagor", ReplyAction="*")]
        double Pisagor(int sayi1, int sayi2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pisagor", ReplyAction="*")]
        System.Threading.Tasks.Task<double> PisagorAsync(int sayi1, int sayi2);
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRssData", ReplyAction="*")]
        WebServisDevam.ServiceReference1.GetRssDataResponse GetRssData(WebServisDevam.ServiceReference1.GetRssDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRssData", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetRssDataResponse> GetRssDataAsync(WebServisDevam.ServiceReference1.GetRssDataRequest request);
        
        // CODEGEN: Generating message contract since element name Url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRssDataWithJsonFormat", ReplyAction="*")]
        WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatResponse GetRssDataWithJsonFormat(WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRssDataWithJsonFormat", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatResponse> GetRssDataWithJsonFormatAsync(WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllMenuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMenu", ReplyAction="*")]
        WebServisDevam.ServiceReference1.GetAllMenuResponse GetAllMenu(WebServisDevam.ServiceReference1.GetAllMenuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMenu", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetAllMenuResponse> GetAllMenuAsync(WebServisDevam.ServiceReference1.GetAllMenuRequest request);
        
        // CODEGEN: Generating message contract since element name GetJsonFormatResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJsonFormat", ReplyAction="*")]
        WebServisDevam.ServiceReference1.GetJsonFormatResponse GetJsonFormat(WebServisDevam.ServiceReference1.GetJsonFormatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJsonFormat", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetJsonFormatResponse> GetJsonFormatAsync(WebServisDevam.ServiceReference1.GetJsonFormatRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTweets", ReplyAction="*")]
        WebServisDevam.ServiceReference1.GetTweetsResponse GetTweets(WebServisDevam.ServiceReference1.GetTweetsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTweets", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetTweetsResponse> GetTweetsAsync(WebServisDevam.ServiceReference1.GetTweetsRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTweetsJson", ReplyAction="*")]
        WebServisDevam.ServiceReference1.GetTweetsJsonResponse GetTweetsJson(WebServisDevam.ServiceReference1.GetTweetsJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTweetsJson", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetTweetsJsonResponse> GetTweetsJsonAsync(WebServisDevam.ServiceReference1.GetTweetsJsonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServisDevam.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServisDevam.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRssDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRssData", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetRssDataRequestBody Body;
        
        public GetRssDataRequest() {
        }
        
        public GetRssDataRequest(WebServisDevam.ServiceReference1.GetRssDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRssDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public GetRssDataRequestBody() {
        }
        
        public GetRssDataRequestBody(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRssDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRssDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetRssDataResponseBody Body;
        
        public GetRssDataResponse() {
        }
        
        public GetRssDataResponse(WebServisDevam.ServiceReference1.GetRssDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRssDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRssDataResult;
        
        public GetRssDataResponseBody() {
        }
        
        public GetRssDataResponseBody(string GetRssDataResult) {
            this.GetRssDataResult = GetRssDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRssDataWithJsonFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRssDataWithJsonFormat", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequestBody Body;
        
        public GetRssDataWithJsonFormatRequest() {
        }
        
        public GetRssDataWithJsonFormatRequest(WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRssDataWithJsonFormatRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Url;
        
        public GetRssDataWithJsonFormatRequestBody() {
        }
        
        public GetRssDataWithJsonFormatRequestBody(string Url) {
            this.Url = Url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRssDataWithJsonFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRssDataWithJsonFormatResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatResponseBody Body;
        
        public GetRssDataWithJsonFormatResponse() {
        }
        
        public GetRssDataWithJsonFormatResponse(WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRssDataWithJsonFormatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRssDataWithJsonFormatResult;
        
        public GetRssDataWithJsonFormatResponseBody() {
        }
        
        public GetRssDataWithJsonFormatResponseBody(string GetRssDataWithJsonFormatResult) {
            this.GetRssDataWithJsonFormatResult = GetRssDataWithJsonFormatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMenuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMenu", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetAllMenuRequestBody Body;
        
        public GetAllMenuRequest() {
        }
        
        public GetAllMenuRequest(WebServisDevam.ServiceReference1.GetAllMenuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMenuRequestBody {
        
        public GetAllMenuRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMenuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMenuResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetAllMenuResponseBody Body;
        
        public GetAllMenuResponse() {
        }
        
        public GetAllMenuResponse(WebServisDevam.ServiceReference1.GetAllMenuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMenuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServisDevam.ServiceReference1.Menu[] GetAllMenuResult;
        
        public GetAllMenuResponseBody() {
        }
        
        public GetAllMenuResponseBody(WebServisDevam.ServiceReference1.Menu[] GetAllMenuResult) {
            this.GetAllMenuResult = GetAllMenuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsonFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsonFormat", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetJsonFormatRequestBody Body;
        
        public GetJsonFormatRequest() {
        }
        
        public GetJsonFormatRequest(WebServisDevam.ServiceReference1.GetJsonFormatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetJsonFormatRequestBody {
        
        public GetJsonFormatRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJsonFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJsonFormatResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetJsonFormatResponseBody Body;
        
        public GetJsonFormatResponse() {
        }
        
        public GetJsonFormatResponse(WebServisDevam.ServiceReference1.GetJsonFormatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetJsonFormatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetJsonFormatResult;
        
        public GetJsonFormatResponseBody() {
        }
        
        public GetJsonFormatResponseBody(string GetJsonFormatResult) {
            this.GetJsonFormatResult = GetJsonFormatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTweetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTweets", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetTweetsRequestBody Body;
        
        public GetTweetsRequest() {
        }
        
        public GetTweetsRequest(WebServisDevam.ServiceReference1.GetTweetsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTweetsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        public GetTweetsRequestBody() {
        }
        
        public GetTweetsRequestBody(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTweetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTweetsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetTweetsResponseBody Body;
        
        public GetTweetsResponse() {
        }
        
        public GetTweetsResponse(WebServisDevam.ServiceReference1.GetTweetsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTweetsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServisDevam.ServiceReference1.Tweet[] GetTweetsResult;
        
        public GetTweetsResponseBody() {
        }
        
        public GetTweetsResponseBody(WebServisDevam.ServiceReference1.Tweet[] GetTweetsResult) {
            this.GetTweetsResult = GetTweetsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTweetsJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTweetsJson", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetTweetsJsonRequestBody Body;
        
        public GetTweetsJsonRequest() {
        }
        
        public GetTweetsJsonRequest(WebServisDevam.ServiceReference1.GetTweetsJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTweetsJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetTweetsJsonRequestBody() {
        }
        
        public GetTweetsJsonRequestBody(string userName) {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTweetsJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTweetsJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServisDevam.ServiceReference1.GetTweetsJsonResponseBody Body;
        
        public GetTweetsJsonResponse() {
        }
        
        public GetTweetsJsonResponse(WebServisDevam.ServiceReference1.GetTweetsJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTweetsJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTweetsJsonResult;
        
        public GetTweetsJsonResponseBody() {
        }
        
        public GetTweetsJsonResponseBody(string GetTweetsJsonResult) {
            this.GetTweetsJsonResult = GetTweetsJsonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceSoapChannel : WebServisDevam.ServiceReference1.MyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceSoapClient : System.ServiceModel.ClientBase<WebServisDevam.ServiceReference1.MyServiceSoap>, WebServisDevam.ServiceReference1.MyServiceSoap {
        
        public MyServiceSoapClient() {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServisDevam.ServiceReference1.HelloWorldResponse WebServisDevam.ServiceReference1.MyServiceSoap.HelloWorld(WebServisDevam.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServisDevam.ServiceReference1.HelloWorldRequest inValue = new WebServisDevam.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.HelloWorldRequestBody();
            WebServisDevam.ServiceReference1.HelloWorldResponse retVal = ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.HelloWorldResponse> WebServisDevam.ServiceReference1.MyServiceSoap.HelloWorldAsync(WebServisDevam.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebServisDevam.ServiceReference1.HelloWorldRequest inValue = new WebServisDevam.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.HelloWorldRequestBody();
            return ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public double Pisagor(int sayi1, int sayi2) {
            return base.Channel.Pisagor(sayi1, sayi2);
        }
        
        public System.Threading.Tasks.Task<double> PisagorAsync(int sayi1, int sayi2) {
            return base.Channel.PisagorAsync(sayi1, sayi2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServisDevam.ServiceReference1.GetRssDataResponse WebServisDevam.ServiceReference1.MyServiceSoap.GetRssData(WebServisDevam.ServiceReference1.GetRssDataRequest request) {
            return base.Channel.GetRssData(request);
        }
        
        public string GetRssData(string url) {
            WebServisDevam.ServiceReference1.GetRssDataRequest inValue = new WebServisDevam.ServiceReference1.GetRssDataRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetRssDataRequestBody();
            inValue.Body.url = url;
            WebServisDevam.ServiceReference1.GetRssDataResponse retVal = ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetRssData(inValue);
            return retVal.Body.GetRssDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetRssDataResponse> WebServisDevam.ServiceReference1.MyServiceSoap.GetRssDataAsync(WebServisDevam.ServiceReference1.GetRssDataRequest request) {
            return base.Channel.GetRssDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetRssDataResponse> GetRssDataAsync(string url) {
            WebServisDevam.ServiceReference1.GetRssDataRequest inValue = new WebServisDevam.ServiceReference1.GetRssDataRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetRssDataRequestBody();
            inValue.Body.url = url;
            return ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetRssDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatResponse WebServisDevam.ServiceReference1.MyServiceSoap.GetRssDataWithJsonFormat(WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequest request) {
            return base.Channel.GetRssDataWithJsonFormat(request);
        }
        
        public string GetRssDataWithJsonFormat(string Url) {
            WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequest inValue = new WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequestBody();
            inValue.Body.Url = Url;
            WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatResponse retVal = ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetRssDataWithJsonFormat(inValue);
            return retVal.Body.GetRssDataWithJsonFormatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatResponse> WebServisDevam.ServiceReference1.MyServiceSoap.GetRssDataWithJsonFormatAsync(WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequest request) {
            return base.Channel.GetRssDataWithJsonFormatAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatResponse> GetRssDataWithJsonFormatAsync(string Url) {
            WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequest inValue = new WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetRssDataWithJsonFormatRequestBody();
            inValue.Body.Url = Url;
            return ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetRssDataWithJsonFormatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServisDevam.ServiceReference1.GetAllMenuResponse WebServisDevam.ServiceReference1.MyServiceSoap.GetAllMenu(WebServisDevam.ServiceReference1.GetAllMenuRequest request) {
            return base.Channel.GetAllMenu(request);
        }
        
        public WebServisDevam.ServiceReference1.Menu[] GetAllMenu() {
            WebServisDevam.ServiceReference1.GetAllMenuRequest inValue = new WebServisDevam.ServiceReference1.GetAllMenuRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetAllMenuRequestBody();
            WebServisDevam.ServiceReference1.GetAllMenuResponse retVal = ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetAllMenu(inValue);
            return retVal.Body.GetAllMenuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetAllMenuResponse> WebServisDevam.ServiceReference1.MyServiceSoap.GetAllMenuAsync(WebServisDevam.ServiceReference1.GetAllMenuRequest request) {
            return base.Channel.GetAllMenuAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetAllMenuResponse> GetAllMenuAsync() {
            WebServisDevam.ServiceReference1.GetAllMenuRequest inValue = new WebServisDevam.ServiceReference1.GetAllMenuRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetAllMenuRequestBody();
            return ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetAllMenuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServisDevam.ServiceReference1.GetJsonFormatResponse WebServisDevam.ServiceReference1.MyServiceSoap.GetJsonFormat(WebServisDevam.ServiceReference1.GetJsonFormatRequest request) {
            return base.Channel.GetJsonFormat(request);
        }
        
        public string GetJsonFormat() {
            WebServisDevam.ServiceReference1.GetJsonFormatRequest inValue = new WebServisDevam.ServiceReference1.GetJsonFormatRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetJsonFormatRequestBody();
            WebServisDevam.ServiceReference1.GetJsonFormatResponse retVal = ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetJsonFormat(inValue);
            return retVal.Body.GetJsonFormatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetJsonFormatResponse> WebServisDevam.ServiceReference1.MyServiceSoap.GetJsonFormatAsync(WebServisDevam.ServiceReference1.GetJsonFormatRequest request) {
            return base.Channel.GetJsonFormatAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetJsonFormatResponse> GetJsonFormatAsync() {
            WebServisDevam.ServiceReference1.GetJsonFormatRequest inValue = new WebServisDevam.ServiceReference1.GetJsonFormatRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetJsonFormatRequestBody();
            return ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetJsonFormatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServisDevam.ServiceReference1.GetTweetsResponse WebServisDevam.ServiceReference1.MyServiceSoap.GetTweets(WebServisDevam.ServiceReference1.GetTweetsRequest request) {
            return base.Channel.GetTweets(request);
        }
        
        public WebServisDevam.ServiceReference1.Tweet[] GetTweets(string UserName) {
            WebServisDevam.ServiceReference1.GetTweetsRequest inValue = new WebServisDevam.ServiceReference1.GetTweetsRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetTweetsRequestBody();
            inValue.Body.UserName = UserName;
            WebServisDevam.ServiceReference1.GetTweetsResponse retVal = ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetTweets(inValue);
            return retVal.Body.GetTweetsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetTweetsResponse> WebServisDevam.ServiceReference1.MyServiceSoap.GetTweetsAsync(WebServisDevam.ServiceReference1.GetTweetsRequest request) {
            return base.Channel.GetTweetsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetTweetsResponse> GetTweetsAsync(string UserName) {
            WebServisDevam.ServiceReference1.GetTweetsRequest inValue = new WebServisDevam.ServiceReference1.GetTweetsRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetTweetsRequestBody();
            inValue.Body.UserName = UserName;
            return ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetTweetsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServisDevam.ServiceReference1.GetTweetsJsonResponse WebServisDevam.ServiceReference1.MyServiceSoap.GetTweetsJson(WebServisDevam.ServiceReference1.GetTweetsJsonRequest request) {
            return base.Channel.GetTweetsJson(request);
        }
        
        public string GetTweetsJson(string userName) {
            WebServisDevam.ServiceReference1.GetTweetsJsonRequest inValue = new WebServisDevam.ServiceReference1.GetTweetsJsonRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetTweetsJsonRequestBody();
            inValue.Body.userName = userName;
            WebServisDevam.ServiceReference1.GetTweetsJsonResponse retVal = ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetTweetsJson(inValue);
            return retVal.Body.GetTweetsJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetTweetsJsonResponse> WebServisDevam.ServiceReference1.MyServiceSoap.GetTweetsJsonAsync(WebServisDevam.ServiceReference1.GetTweetsJsonRequest request) {
            return base.Channel.GetTweetsJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServisDevam.ServiceReference1.GetTweetsJsonResponse> GetTweetsJsonAsync(string userName) {
            WebServisDevam.ServiceReference1.GetTweetsJsonRequest inValue = new WebServisDevam.ServiceReference1.GetTweetsJsonRequest();
            inValue.Body = new WebServisDevam.ServiceReference1.GetTweetsJsonRequestBody();
            inValue.Body.userName = userName;
            return ((WebServisDevam.ServiceReference1.MyServiceSoap)(this)).GetTweetsJsonAsync(inValue);
        }
    }
}
